In [1]:
import pennylane as qml
import pennylane.numpy as np

In [3]:
#qml.matrix(qml.RY(0.2*np.pi,0)@qml.PauliX(0)@qml.RY(-0.2*np.pi,0))

array([[-0.58778525+0.j,  0.80901699+0.j],
       [ 0.80901699+0.j,  0.58778525+0.j]])

In [9]:
X=(np.load('./saved_data_PneumoniaMNIST/train_seqs_42.npz')['arr_0']) # train images

train_label=np.load('./saved_data_PneumoniaMNIST/train_labels.npz')['arr_0']


Y = np.array([int(y) for y in train_label]) # train lables
Y = Y * 2 - np.ones(len(Y)) # shift label from {0, 1} to {-1, 1}

In [10]:
X_list = [X[i, 0, :, :] for i in range(10)]
X = X_list
Y_list = [Y[i] for i in range(10)]
Y = Y_list

In [25]:
X[0]

array([[0.36078431, 0.42352941, 0.45882353, 0.43529412, 0.39607843,
        0.35294118, 0.2745098 , 0.19215686, 0.10980392, 0.23529412,
        0.3254902 , 0.46666667, 0.61176471, 0.72941176, 0.82745098,
        0.8       , 0.75294118, 0.79607843, 0.8       , 0.65098039,
        0.45098039, 0.35294118, 0.20784314, 0.        , 0.        ,
        0.01960784, 0.03137255, 0.02352941],
       [0.50588235, 0.54117647, 0.55294118, 0.51764706, 0.47058824,
        0.43529412, 0.39215686, 0.34901961, 0.38039216, 0.43137255,
        0.41176471, 0.45882353, 0.56470588, 0.67843137, 0.76470588,
        0.70980392, 0.76078431, 0.75686275, 0.69803922, 0.55686275,
        0.43137255, 0.36078431, 0.22352941, 0.04313725, 0.02352941,
        0.01568627, 0.00784314, 0.01176471],
       [0.55294118, 0.57254902, 0.58039216, 0.56078431, 0.5254902 ,
        0.50196078, 0.49411765, 0.49411765, 0.54901961, 0.61176471,
        0.56078431, 0.5372549 , 0.56470588, 0.63529412, 0.70588235,
        0.64705882, 0.6235

In [4]:
#qml.matrix(qml.RY(0.2*np.pi,0)@qml.RY(-0.2*np.pi,0))

array([[1.00000000e+00+0.j, 1.19889621e-17+0.j],
       [1.19889621e-17+0.j, 1.00000000e+00+0.j]])

In [12]:
index_x=['x0','x1','x2','x3','x4']
index_y=['y0','y1','y2','y3','y4']
def encoder(image):
    for wire in (index_x+index_y):
        qml.Hadamard(wires=wire)
    for i in range(len(image)):
        y = bin(i)[2:]
        y = '0'*(5-len(y)) + y
        for j in range(len(image[0])):
            if image[i][j]>0.001:
                x = bin(j)[2:]
                x = '0'*(5-len(x)) + x
                qml.RY(image[i][j]/2*np.pi,wires='gray')
                qml.MultiControlledX(control_wires=(index_x+index_y), wires='gray', control_values=x+y)
                qml.RY(image[i][j]/2*np.pi,wires='gray')
            
            

In [13]:
def entangling_layer0(input_wires,output_wires,weights):
    
    weights_ = (weight for weight in weights)
    for i in input_wires:
        for j in output_wires:
            qml.CNOT(wires=[i,j])
            
            param = next(weights_)
            qml.RZ(param, wires=j)
            
            param = next(weights_)
            qml.RX(param, wires=j) 
            
            qml.CNOT(wires=[i,j])
            


In [14]:
def entangling_layer1(wires,weights):
    n=len(wires)
    weights_ = (weight for weight in weights)
    for i in range(1,n):
        j = 0
        r = []
        while j <= n-1:
            if j not in r:
                qml.CNOT([wires[j],wires[j+i]])
                r += [j+1]
            
                param = next(weights_)
                qml.RZ(param, wires=j)
            
                param = next(weights_)
                qml.RX(param, wires=j) 
            
                qml.CNOT([wires[j],wires[j+i]])
                j += 1
        for j in r:
            qml.CNOT([wires[j],wires[j+i]])
            
            param = next(weights_)
            qml.RZ(param, wires=j)
            
            param = next(weights_)
            qml.RX(param, wires=j) 
            
            qml.CNOT([wires[j],wires[j+i]])

In [15]:
'''
wires = [0,1,2,3]
np.random.seed(0)
weights= 0.01 * np.random.randn(12, requires_grad=True)

dev = qml.device("default.qubit", wires=wires)
@qml.qnode(dev)

def entangling_layer1(wires,weights):
    n=len(wires)
    weights_ = (weight for weight in weights)
    for i in range(1,n):
        j = 0
        r = []
        while j <= n-i-1:
            if j not in r:
                qml.CNOT([wires[j],wires[j+i]])
                r += [j+1]
            
                param = next(weights_)
                qml.RZ(param, wires=j)
            
                param = next(weights_)
                qml.RX(param, wires=j) 
            
                qml.CNOT([wires[j],wires[j+i]])
            j += 1
        for j in r:
            if j+i <= n-1:
                qml.CNOT([wires[j],wires[j+i]])
            
                param = next(weights_)
                qml.RZ(param, wires=j)
            
                param = next(weights_)
                qml.RX(param, wires=j) 
            
                qml.CNOT([wires[j],wires[j+i]])
    return qml.probs(wires[0])
            
print(qml.draw(entangling_layer1)(wires,weights))'''

'\nwires = [0,1,2,3]\nnp.random.seed(0)\nweights= 0.01 * np.random.randn(12, requires_grad=True)\n\ndev = qml.device("default.qubit", wires=wires)\n@qml.qnode(dev)\n\ndef entangling_layer1(wires,weights):\n    n=len(wires)\n    weights_ = (weight for weight in weights)\n    for i in range(1,n):\n        j = 0\n        r = []\n        while j <= n-i-1:\n            if j not in r:\n                qml.CNOT([wires[j],wires[j+i]])\n                r += [j+1]\n            \n                param = next(weights_)\n                qml.RZ(param, wires=j)\n            \n                param = next(weights_)\n                qml.RX(param, wires=j) \n            \n                qml.CNOT([wires[j],wires[j+i]])\n            j += 1\n        for j in r:\n            if j+i <= n-1:\n                qml.CNOT([wires[j],wires[j+i]])\n            \n                param = next(weights_)\n                qml.RZ(param, wires=j)\n            \n                param = next(weights_)\n                qml.RX

In [16]:
# The training circuit
encoder_wires = ['x0','x1','x2','x3','x4','y0','y1','y2','y3','y4','gray','train']
dev = qml.device("default.qubit", wires=encoder_wires)
@qml.qnode(dev)
def circuit(weights, image):
    encoder(image)
    entangling_layer0(['x0','x1','x2','x3','x4','y0','y1','y2','y3','y4','gray'],['train'],weights)
    #entangling_layer1(['x0','x1','x2','x3','x4','y0','y1','y2','y3','y4','gray'],weights)
    return qml.expval(qml.PauliZ('train'))



In [17]:
def variational_classifier(weights, bias, x):
    return circuit(weights, x) + bias

In [18]:
def square_loss(labels, predictions):
    loss = 0
    for l, p in zip(labels, predictions):
        loss = loss + (l - p) ** 2

    loss = loss / len(labels)
    return loss

In [19]:
def accuracy(labels, predictions):

    loss = 0
    for l, p in zip(labels, predictions):
        if abs(l - p) < 1e-5:
            loss = loss + 1
    loss = loss / len(labels)

    return loss

In [20]:
def cost(weights, bias, X, Y):
    predictions = [variational_classifier(weights, bias, x) for x in X]
    return square_loss(Y, predictions)

In [21]:
np.random.seed(0)
weights_init = 0.01 * np.random.randn(22, requires_grad=True)
#weights_init = 0.01 * np.random.randn(110, requires_grad=True)
bias_init = np.array(0.0, requires_grad=True)

In [22]:
from pennylane.optimize import NesterovMomentumOptimizer
opt = NesterovMomentumOptimizer(0.5)
batch_size = 2

In [23]:
# Training the circuit
weights = weights_init
bias = bias_init
for it in range(2):

    # Update the weights by one optimizer step
    batch_index = np.random.randint(0, len(X), (batch_size,))
    X_batch = X[batch_index]
    Y_batch = Y[batch_index]
    weights, bias, _, _ = opt.step(cost, weights, bias, X_batch, Y_batch)

    # Compute accuracy
    predictions = [np.sign(variational_classifier(weights, bias, x)) for x in X]
    acc = accuracy(Y, predictions)

    print(
        "Iter: {:5d} | Cost: {:0.7f} | Accuracy: {:0.7f} ".format(
            it + 1, cost(weights, bias, X, Y), acc
        )
    )

TypeError: only integer scalar arrays can be converted to a scalar index

In [ ]:
# test model with test dataset

test_X=(np.load('images.npy')*255)[495:505] # train images

test_label=np.load('labels.npy')[495:505]
test_Y = np.array([int(y) for y in test_label]) # train lables
test_Y = test_Y * 2 - np.ones(len(test_Y)) # shift label from {0, 1} to {-1, 1}

In [ ]:
test_predictions = [np.sign(variational_classifier(weights, bias, x)) for x in test_X]
test_acc = accuracy(test_Y, test_predictions)